### cXML setup
POST http://yves.eu.spryker.local/punchout-gateway/cxml/setup
Referer: https://some-platform.com/internal-url/with-a-path/
Cookie: XDEBUG_SESSION=PHPSTORM

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cXML SYSTEM "http://xml.cxml.org/schemas/cXML/1.2.041/cXML.dtd">
<cXML payloadID="1774880675.6043@punchoutcommerce.com" timestamp="2026-03-30T14:24:35+00:00">
  <Header>
    <From>
      <Credential domain="NetworkId">
        <Identity></Identity>
      </Credential>
    </From>
    <To>
      <Credential domain="DUNS">
        <Identity></Identity>
      </Credential>
    </To>
    <Sender>
      <Credential domain="NetworkId">
        <Identity>MyIdentity</Identity>
        <SharedSecret>jd8je3$ndP</SharedSecret>
      </Credential>
      <UserAgent>PunchOutCommerce PunchOut Tester</UserAgent>
    </Sender>
  </Header>
  <Request deploymentMode="production">
    <PunchOutSetupRequest operation="create">
      <BuyerCookie>d0be9804478c3f1f52871d4eba9fb035</BuyerCookie>
      <Extrinsic name="User">jdoe12345</Extrinsic>
      <Extrinsic name="UniqueUsername">jdoe12345</Extrinsic>
      <Extrinsic name="UserId">12345</Extrinsic>
      <Extrinsic name="UserEmail">jdoe@example.com</Extrinsic>
      <Extrinsic name="UserFullName">John Doe</Extrinsic>
      <Extrinsic name="UserPrintableName">John Doe</Extrinsic>
      <Extrinsic name="FirstName">John</Extrinsic>
      <Extrinsic name="LastName">Doe</Extrinsic>
      <Extrinsic name="PhoneNumber">555-555-5555</Extrinsic>
      <BrowserFormPost>
        <URL>https://punchoutcommerce.com/tools/cxml-punchout-return</URL>
      </BrowserFormPost>
      <SupplierSetup>
        <URL>https://webhook.site/8712edbf-d40a-4c1c-9bf7-a1193aa15061</URL>
      </SupplierSetup>
      <ShipTo>
        <Address addressID="TEST">
          <Name xml:lang="en">TEST</Name>
          <PostalAddress>
            <Street>123 Street Address</Street>
            <City>Rockville</City>
            <State>MD</State>
            <PostalCode>20850</PostalCode>
            <Country isoCountryCode="US">US</Country>
          </PostalAddress>
        </Address>
      </ShipTo>
    </PunchOutSetupRequest>
  </Request>
</cXML>


### cXML setup
POST http://yves.eu.spryker.local/punchout-gateway/cxml/setup
Referer: https://some-platform.com/internal-url/with-a-path/
Cookie: XDEBUG_SESSION=PHPSTORM

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cXML SYSTEM "http://xml.cxml.org/schemas/cXML/1.2.041/cXML.dtd">
<cXML payloadID="1773914411.573@punchoutcommerce.com" timestamp="2026-03-19T10:00:11+00:00">
  <Header>
    <From>
      <Credential domain="NetworkId">
        <Identity></Identity>
      </Credential>
    </From>
    <To>
      <Credential domain="DUNS">
        <Identity></Identity>
      </Credential>
    </To>
    <Sender>
      <Credential domain="NetworkId">
        <Identity>MyIdentity</Identity>
        <SharedSecret>jd8je3$ndP</SharedSecret>
      </Credential>
      <UserAgent>PunchOutCommerce PunchOut Tester</UserAgent>
    </Sender>
  </Header>
  <Request deploymentMode="production">
    <PunchOutSetupRequest operation="create">
      <BuyerCookie>a213c9c0ab80b3c5b5263fa422015623</BuyerCookie>
      <Extrinsic name="User">jdoe12345</Extrinsic>
      <Extrinsic name="UniqueUsername">jdoe12345</Extrinsic>
      <Extrinsic name="UserId">12345</Extrinsic>
      <Extrinsic name="UserEmail">spencor.hopkin@spryker.com</Extrinsic>
      <Extrinsic name="UserFullName">John Doe</Extrinsic>
      <Extrinsic name="UserPrintableName">John Doe</Extrinsic>
      <Extrinsic name="FirstName">John</Extrinsic>
      <Extrinsic name="LastName">Doe</Extrinsic>
      <Extrinsic name="PhoneNumber">555-555-5555</Extrinsic>
      <BrowserFormPost>
        <URL>https://punchoutcommerce.com/tools/cxml-punchout-return</URL>
      </BrowserFormPost>
      <SupplierSetup>
        <URL>http://yves.eu.spryker.local/punchout-gateway/cxml/setup</URL>
      </SupplierSetup>
      <ShipTo>
        <Address addressID="TEST">
          <Name xml:lang="en">TEST</Name>
          <PostalAddress>
            <Street>123 Street Address</Street>
            <City>Rockville</City>
            <State>MD</State>
            <PostalCode>20850</PostalCode>
            <Country isoCountryCode="US">US</Country>
          </PostalAddress>
        </Address>
      </ShipTo>
    </PunchOutSetupRequest>
  </Request>
</cXML>


### cXML Start
GET http://yves.eu.spryker.local/punchout-gateway/cxml/start?session=69c40d4ec0a37
Cookie: XDEBUG_SESSION=PHPSTORM


### OCI setup
POST http://yves.eu.spryker.local/punchout-gateway/oci/company1
Cookie: XDEBUG_SESSION=PHPSTORM
Content-Type: application/x-www-form-urlencoded

USERNAME=username&PASSWORD=password&HOOK_URL=https%3A%2F%2Fpunchoutcommerce.com%2Ftools%2Foci-roundtrip-return&%7ETARGET=_top&%7EOkCode=ADDI&%7ECALLER=CTLG


